<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="54274" started-at="2017-04-16T18:07:32Z" finished-at="2017-04-16T18:08:27Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="54274" started-at="2017-04-16T18:07:32Z" finished-at="2017-04-16T18:08:27Z">
      <class name="TestCases.TC001_LoginValidation">
        <test-method status="PASS" signature="setup()[pri:0, instance:TestCases.TC001_LoginValidation@47c62251]" name="setup" is-config="true" duration-ms="18521" started-at="2017-04-16T23:37:32Z" finished-at="2017-04-16T23:37:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testAppTitle()[pri:0, instance:TestCases.TC001_LoginValidation@47c62251]" name="testAppTitle" duration-ms="1284" started-at="2017-04-16T23:37:51Z" finished-at="2017-04-16T23:37:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAppTitle -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCases.TC001_LoginValidation@47c62251]" name="tearDown" is-config="true" duration-ms="1594" started-at="2017-04-16T23:37:52Z" finished-at="2017-04-16T23:37:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testAppTitle status=SUCCESS method=TC001_LoginValidation.testAppTitle()[pri:0, instance:TestCases.TC001_LoginValidation@47c62251] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:TestCases.TC001_LoginValidation@47c62251]" name="setup" is-config="true" duration-ms="14132" started-at="2017-04-16T23:37:54Z" finished-at="2017-04-16T23:38:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testLogin()[pri:0, instance:TestCases.TC001_LoginValidation@47c62251]" name="testLogin" duration-ms="17496" started-at="2017-04-16T23:38:08Z" finished-at="2017-04-16T23:38:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestCases.TC001_LoginValidation.testLogin(TC001_LoginValidation.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCases.TC001_LoginValidation@47c62251]" name="tearDown" is-config="true" duration-ms="1176" started-at="2017-04-16T23:38:25Z" finished-at="2017-04-16T23:38:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=FAILURE method=TC001_LoginValidation.testLogin()[pri:0, instance:TestCases.TC001_LoginValidation@47c62251] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TC001_LoginValidation -->
    </test> <!-- LoginTest -->
  </suite> <!-- Suite -->
</testng-results>
